### ISSUE TITLE
Reconciliation fails when no user data is provided

### ISSUE THREAD

**Issue by simplysoft** [sp-yduck/cluster-api-provider-proxmox#83]
When `ProxmoxMachineTemplate` does not contain `spec.template.spec.cloudInit.user`, the merging (and thus reconciliation) fails, even though omitting of that field is allowed according to the spec. 

As a workaround adding empty map solves this issue:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ProxmoxMachineTemplate
metadata:
  [...]
spec:
  template:
    spec:
      [...]
      cloudInit:
        user: {}
```

The underlying issue can be reproduced with code: 
`mergeUserDatas(bootstrapConfig, baseUserData(vmName), &infrav1.UserData{})` works, but  `mergeUserDatas(bootstrapConfig, baseUserData(vmName), nil)` doesn't 

Either that cases should be handeled or the spec adjusted to not allow omitting that field 

**Environment:**
- Cluster-api-provider-proxmox version: 0.3.0
